#!/bin/sh
# Common startup, sourced by every start_apps/<hostname>.<user> script:
# daemons that have no systemd unit + per-session X setup.

~/.screenlayout/home.sh &
clipcatd &
redshift-gtk &
"$HOME/.config/wallpaper/grid-wall" &
numlockx &
pasystray &

# Terminal at login (both users); honour $TERMINAL, default to alacritty
${TERMINAL:-alacritty} &

# Touchpad tuning (aurora hardware)
xinput set-prop 'SynPS/2 Synaptics TouchPad' 'libinput Accel Speed' 0.7
xinput set-prop 'SynPS/2 Synaptics TouchPad' 'libinput Tapping Enabled' 1

# Custom user fonts
xset +fp /home/$USER/.local/share/fonts
xset fp rehash
