#!/bin/sh
# Common startup, sourced by every start_apps/<hostname>.<user> script:
# daemons that have no systemd unit + per-session X setup.

~/.screenlayout/home.sh &
clipcatd &
redshift-gtk &
feh --bg-fill $(find -L /usr/share/wallpapers | shuf | head -n 1)
numlockx &
pasystray &

# Touchpad tuning (aurora hardware)
xinput set-prop 'SynPS/2 Synaptics TouchPad' 'libinput Accel Speed' 0.7
xinput set-prop 'SynPS/2 Synaptics TouchPad' 'libinput Tapping Enabled' 1

# Custom user fonts
xset +fp /home/$USER/.local/share/fonts
xset fp rehash
